# Generated by Django 5.0.2 on 2024-02-10 07:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='relationship',
            field=models.CharField(default='친구/지인', max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='senderAddr1',
            field=models.CharField(default='경상남도 진주시 금산면 송백로 46', max_length=200),
        ),
        migrations.AlterField(
            model_name='letter',
            name='senderAddr2',
            field=models.CharField(default='사서함', max_length=200),
        ),
        migrations.AlterField(
            model_name='letter',
            name='senderName',
            field=models.CharField(default='ㅇㅇ', max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='senderZipcode',
            field=models.CharField(default='52364', max_length=7),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
