# Generated by Django 5.0.2 on 2024-03-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_id_alter_user_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='temp_id',
            new_name='id',
        ),
    ]
