# Generated by Django 5.0.2 on 2024-02-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_trainee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='reserved_date',
            new_name='date',
        ),
    ]
