# Generated by Django 5.0.2 on 2024-02-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_date_letter_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='relationship',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='senderAddr1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='letter',
            name='senderAddr2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='letter',
            name='senderName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='senderZipcode',
            field=models.CharField(max_length=7),
        ),
    ]
