# Generated by Django 5.0.2 on 2024-02-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_letter_relationship_alter_letter_senderaddr1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='senderAddr1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='letter',
            name='senderAddr2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='letter',
            name='senderName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='senderZipcode',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
