# Generated by Django 5.0.2 on 2024-02-13 01:59

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_letter_relationship_alter_letter_senderaddr1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=api.models.IntEnumField(default=0, enum=api.models.LetterStatus),
        ),
    ]
